CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name    VARCHAR(60) NOT NULL,
    CONSTRAINT uk_categories_user_name UNIQUE (user_id, name)
);

CREATE TABLE expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id BIGINT         REFERENCES categories (id) ON DELETE SET NULL,
    amount      NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    description VARCHAR(255),
    spent_on    DATE           NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_expenses_user_spent_on ON expenses (user_id, spent_on);
CREATE INDEX idx_expenses_category ON expenses (category_id);
